name: Publish to PyPI

on:
  release:
    types: [published]
  push:
    tags:
      - 'v*'

jobs:
  pypi-publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Git taglerini tam çekmek için

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Extract version from Tag
        id: get_version
        run: |
          # GITHUB_REF_NAME "v0.1.1" -> "0.1.1"
          VERSION="${GITHUB_REF_NAME#v}"
          echo "PKG_VERSION=$VERSION" >> $GITHUB_ENV
          echo "Publishing version: $VERSION"

      - name: Install dependencies & run tests
        run: |
          uv sync --all-extras
          uv run pytest
        env:
          FINTABLES_EMAIL: ${{ secrets.FINTABLES_EMAIL }}
          FINTABLES_PASSWORD: ${{ secrets.FINTABLES_PASSWORD }}

      - name: Build package with dynamic version
        run: uv build
        env:
          SETUPTOOLS_SCM_PRETEND_VERSION: ${{ env.PKG_VERSION }}

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
